/*
 * TablaDDatos.java
 *
 * Created on 10 de mayo de 2008, 8:08
 */

package editortp;



import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import java.util.Vector;

import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JTable;



import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author  ALF
 */
public class TablaDDatos extends javax.swing.JPanel {
    
    /** Creates new form TablaDDatos */
    private Vector<Vector> filas = new Vector<Vector>();


    private Vector<String> columnas = new Vector<String>();
    //
      JFileChooser selectorArchivos = new JFileChooser();
    //private int numerodefilasActivadas=0;

    
    public TablaDDatos() {
        initComponents();
        columnas.add("Por Defecto");
        columnas.add("Ruta programa");
        columnas.add("Comando");
        columnas.add("Entrada archivo");


        
        jTable1.setModel(new DefaultTableModel(filas,columnas) {
			 		Class[] types = new Class [] {
		                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
		            };
		            boolean[] canEdit = new boolean [] {
		               true,true,true,true
		            };
		            public Class getColumnClass(int columnIndex) {
		                return types [columnIndex];
		            }
		            public boolean isCellEditable(int rowIndex, int columnIndex) {
		                return canEdit [columnIndex];
		            }
			});

           
             String  ruta [] ={""};
             final   JComboBox cb1=new JComboBox(ruta);
             cb1.addMouseListener(new MouseAdapter() {
                            @Override
                            public void mouseReleased(MouseEvent e) {
                                    int aprovado = selectorArchivos.showDialog(null, "Archivos");
                                    if (aprovado == JFileChooser.APPROVE_OPTION) {
                                        String dir = selectorArchivos.getSelectedFile().getAbsolutePath();
                                        cb1.addItem(dir);
                                    }
                            }
                            @Override
                            public void mousePressed(MouseEvent e) {
                                   cb1.removeAllItems();

                            }
           });


            TableColumn column1 = jTable1.getColumn("Ruta programa");
            column1.setCellEditor(new DefaultCellEditor(cb1));

            String  opcionesEntrada [] ={"Nombre","Nombre y extención"};
            JComboBox cb=new JComboBox(opcionesEntrada);

         TableColumn column3 = jTable1.getColumn("Entrada archivo");
        column3.setCellEditor(new DefaultCellEditor(cb));

    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Puntos seleccionados", "Puntos", "x", "f(x)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    public double[] getXseleccionados(){
        double x[]= new double [getNumeroDfilasActivadas()];
        int j=0;
        for (int i = 0; i < filas.size(); i++) {
            if(Boolean.parseBoolean(filas.get(i).get(0).toString())==true){
                x[j]=Double.parseDouble(filas.get(i).get(2).toString());
                j++;
            }
        }

        return x;
    }
    public double[][] getFXseleccionados(){
        double x[][]= new double [getNumeroDfilasActivadas()][1];
        int j=0;
        for (int i = 0; i < filas.size(); i++) {
            if(Boolean.parseBoolean(filas.get(i).get(0).toString())==true){
                x[j][0]=Double.parseDouble(filas.get(i).get(3).toString());
                j++;
            }
        }
        return x;
    }
    public  int getNumeroDfilasActivadas(){
        int aux=0;
        for (int i = 0; i < filas.size(); i++) {
            if(Boolean.parseBoolean(filas.get(i).get(0).toString())==true)
                aux++;
        }
        return aux;
    }

    public int getFilaSeleccionada(){
        int x=-1;

         for (int i = 0; i < filas.size(); i++) {
            if(Boolean.parseBoolean(filas.get(i).get(0).toString())==true){
                  x=i;
                  break;
            }
        }

        return x;
    }
    ///*************************************************************
     public Vector<String> getColumnas() {
        return columnas;
    }

    public Vector<Vector> getFilas() {
        return filas;
    }
    
    public void addNuevaFila(Vector<Object> f){
        filas.add(f);
        jTable1.revalidate();
                
    }
     public void removerFila(int i){
        filas.remove(i);
        jTable1.revalidate();
                
    }
     //***************************
      public void setFilas(Vector<Vector> filasx) {
          filas.removeAllElements();
          for (int i = 0; i < filasx.size(); i++) {
              filas.add(filasx.get(i));
          }
          jTable1.revalidate();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public JTable getJTable1() {
        return jTable1;
    }
    
}
